name 'base-chef'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures base-chef'
long_description 'Installs/Configures base-chef'
version '0.1.0'

depends 'auditd'
depends 'iptables'
depends 'hostname'
depends 'ntp'
depends 'selinux'
depends 'sysctl'
depends 'sudo'
depends 'timezone_lwrp'
